'use strict';
const canvas=document.getElementById('glCanvas'), gl=canvas.getContext('webgl',{antialias:true,alpha:false});
if(!gl){document.body.innerHTML='<div style="padding:30px;color:white;font-family:Arial">متصفحك لا يدعم WebGL.</div>';throw new Error('WebGL unavailable');}
const vs=`attribute vec2 a; uniform vec2 s; void main(){vec2 p=a/s*2.0-1.0; gl_Position=vec4(p.x,-p.y,0.0,1.0);}`;
const fs=`precision mediump float; uniform vec4 c; void main(){gl_FragColor=c;}`;
function sh(type,src){let x=gl.createShader(type);gl.shaderSource(x,src);gl.compileShader(x);return x}const prog=gl.createProgram();gl.attachShader(prog,sh(gl.VERTEX_SHADER,vs));gl.attachShader(prog,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);gl.useProgram(prog);
const buf=gl.createBuffer(), apos=gl.getAttribLocation(prog,'a'), us=gl.getUniformLocation(prog,'s'), uc=gl.getUniformLocation(prog,'c');gl.enableVertexAttribArray(apos);gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.vertexAttribPointer(apos,2,gl.FLOAT,false,0,0);
function resize(){const d=devicePixelRatio||1;canvas.width=innerWidth*d;canvas.height=innerHeight*d;gl.viewport(0,0,canvas.width,canvas.height);gl.uniform2f(us,canvas.width,canvas.height)}addEventListener('resize',resize);resize();
const kingdoms=[{name:'مملكتك',color:[.85,.65,.13,1],gold:5000},{name:'الإمبراطورية الشمالية',color:[.2,.4,.9,1],gold:5000},{name:'سلطنة الصحراء',color:[.9,.2,.2,1],gold:5000},{name:'عشائر الجبال',color:[.2,.7,.3,1],gold:5000}];
const cities=[
{name:'دمشق',x:-30,z:20,k:1,g:50,w:1,castle:false},{name:'بغداد',x:40,z:-10,k:2,g:50,w:1,castle:false},{name:'القاهرة',x:-40,z:-30,k:3,g:50,w:1,castle:false},{name:'قلعتك',x:0,z:0,k:0,g:30,w:3,castle:true},{name:'حلب',x:-10,z:40,k:1,g:50,w:1,castle:false},{name:'صنعاء',x:50,z:30,k:2,g:50,w:1,castle:false}];
const types=[['مشاة',50,5,100,10,5],['رماة',80,8,80,15,3],['فرسان',150,15,150,25,15],['نبلاء',300,30,200,35,25]];
let state={day:1,gold:2000,morale:100,troops:[],x:0,z:0,phase:'map',battle:null};
let relations={};for(let i=0;i<4;i++)for(let j=0;j<4;j++)if(i!==j)relations[i+','+j]='neutral';
const logEl=document.getElementById('log'),panel=document.getElementById('panel');
function log(t){let d=document.createElement('div');d.className='msg';d.textContent=t;logEl.prepend(d);while(logEl.children.length>6)logEl.lastChild.remove()}
function ui(){document.getElementById('day').textContent='اليوم '+state.day;document.getElementById('gold').textContent='💰 '+state.gold;document.getElementById('morale').textContent='❤️ '+Math.max(0,Math.round(state.morale))}
function rel(a,b){return relations[a+','+b]||'neutral'}function war(a,b){relations[a+','+b]=relations[b+','+a]='war'}
function worldToScreen(x,z){const scale=Math.min(innerWidth,innerHeight)/170;return [innerWidth/2+(x-state.x)*scale,innerHeight/2+(z-state.z)*scale]}
function rect(x,y,w,h,c){let v=new Float32Array([x,y,x+w,y,x,y+h,x,y+h,x+w,y,x+w,y+h]);gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,v,gl.STREAM_DRAW);gl.uniform4f(uc,...c);gl.drawArrays(gl.TRIANGLES,0,6)}
function circle(x,y,r,c){const n=24,v=[];for(let i=0;i<n;i++){let a=i*Math.PI*2/n,b=(i+1)*Math.PI*2/n;v.push(x,y,x+Math.cos(a)*r,y+Math.sin(a)*r,x+Math.cos(b)*r,y+Math.sin(b)*r)}gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(v),gl.STREAM_DRAW);gl.uniform4f(uc,...c);gl.drawArrays(gl.TRIANGLES,0,n*3)}
function render(){gl.clearColor(.48,.69,.88,1);gl.clear(gl.COLOR_BUFFER_BIT);let s=Math.min(innerWidth,innerHeight)/170;
 if(state.phase==='battle'){renderBattle();requestAnimationFrame(render);return}
 rect(0,innerHeight*.18,innerWidth,innerHeight*.82,[.73,.62,.39,1]);
 // roads
 for(let x=-80;x<=80;x+=20){let [sx]=worldToScreen(x,-80);rect(sx-1,innerHeight*.18,2,innerHeight*.82,[.62,.51,.31,1])}
 for(const c of cities){let [sx,sy]=worldToScreen(c.x,c.z);if(sx<-30||sx>innerWidth+30||sy<innerHeight*.18-30||sy>innerHeight+30)continue;circle(sx,sy,c.castle?17:12,kingdoms[c.k].color);rect(sx-5,sy-5,10,10,[.15,.12,.1,1]);}
 let [px,py]=worldToScreen(state.x,state.z);circle(px,py,9,[1,.9,.2,1]);rect(px-3,py-12,6,24,[.25,.18,.08,1]);ui();requestAnimationFrame(render)}
function renderBattle(){rect(0,0,innerWidth,innerHeight,[.46,.39,.27,1]);let b=state.battle;circle(innerWidth*.2,innerHeight*.55,Math.min(45,innerWidth*.07),kingdoms[0].color);circle(innerWidth*.8,innerHeight*.55,Math.min(45,innerWidth*.07),kingdoms[b.enemyK].color);for(let i=0;i<Math.min(b.player,20);i++)circle(innerWidth*.18+(i%5)*18,innerHeight*.55+Math.floor(i/5)*18,6,kingdoms[0].color);for(let i=0;i<Math.min(b.enemy,20);i++)circle(innerWidth*.78+(i%5)*18,innerHeight*.55+Math.floor(i/5)*18,6,kingdoms[b.enemyK].color);rect(innerWidth*.25,innerHeight*.18,innerWidth*.5,12,[.1,.1,.1,1]);rect(innerWidth*.25,innerHeight*.18,innerWidth*.5*(b.player/Math.max(1,b.startPlayer)),12,[.2,.85,.35,1]);}
function nearestCity(){let best=null,bd=999;for(const c of cities){let d=Math.hypot(c.x-state.x,c.z-state.z);if(d<bd){bd=d;best=c}}return bd<10?best:null}
function cityPanel(c){panel.classList.remove('hidden');let owner=kingdoms[c.k];panel.innerHTML=`<h2>${c.castle?'🏰':'🏘️'} ${c.name}</h2><div class="stat"><span>المالك</span><b>${owner.name}</b></div><div class="stat"><span>الحامية</span><b>${c.g}</b></div><div class="stat"><span>الجدار</span><b>${c.w}</b></div><p>اقترب من المدينة أكثر ثم اختر الإجراء المناسب.</p><button id="attack">⚔️ مهاجمة المدينة</button><button id="recruit">🪖 التجنيد</button><button id="close">إغلاق</button>`;
 document.getElementById('close').onclick=()=>panel.classList.add('hidden');document.getElementById('recruit').onclick=()=>recruitPanel(c);document.getElementById('attack').onclick=()=>{panel.classList.add('hidden');startBattle(c)};}
function recruitPanel(c){panel.innerHTML='<h2>🪖 التجنيد</h2>'+types.map((t,i)=>`<div class="unit"><b>${t[0]}</b> — ${t[1]} ذهب — قوة ${t[4]}<button data-r="${i}">تجنيد 1</button></div>`).join('')+'<button id="close">إغلاق</button>';document.getElementById('close').onclick=()=>panel.classList.add('hidden');panel.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{let i=+b.dataset.r,t=types[i];if(state.troops.length>=50)return log('الجيش ممتلئ');if(state.gold<t[1])return log('لا يوجد ذهب كافٍ');state.gold-=t[1];state.troops.push(i);ui();log('تم تجنيد '+t[0]);});}
function startBattle(c){if(c.k===0)return log('هذه مدينتك');if(rel(0,c.k)!=='war')war(0,c.k);let p=Math.max(1,state.troops.length), enemy=Math.max(8,Math.round(c.g*(c.castle?1.25:1)));state.phase='battle';state.battle={city:c,enemyK:c.k,player:p,enemy,startPlayer:p};document.getElementById('endBattle').classList.remove('hidden');log('بدأت معركة '+c.name+'!');}
function resolveBattle(){let b=state.battle,power=state.troops.reduce((a,i)=>a+types[i][4]+types[i][5],0)*(state.morale/100),enemyPower=b.enemy*(b.city.w*4+12);if(power>enemyPower){b.city.k=0;b.city.g=Math.max(10,Math.round(b.player/3));log('🏆 انتصرت واحتللت '+b.city.name);state.gold+=300;state.morale=Math.min(100,state.morale+5)}else{state.troops=state.troops.slice(0,Math.max(0,Math.floor(state.troops.length*.65)));state.morale=Math.max(0,state.morale-15);log('❌ خسرت المعركة');}state.phase='map';state.battle=null;document.getElementById('endBattle').classList.add('hidden');ui()}
function move(dx,dz){if(state.phase!=='map')return;state.x=Math.max(-80,Math.min(80,state.x+dx));state.z=Math.max(-80,Math.min(80,state.z+dz));let c=nearestCity();if(c)cityPanel(c)}
function save(){localStorage.setItem('desertKnightSave',JSON.stringify({state,cities,relations}));log('تم حفظ اللعبة')}
function load(){let x=localStorage.getItem('desertKnightSave');if(!x)return log('لا يوجد حفظ');let d=JSON.parse(x);state=d.state;for(let i=0;i<cities.length;i++)Object.assign(cities[i],d.cities[i]);relations=d.relations;ui();log('تم تحميل اللعبة')}
['up','down','left','right'].forEach(k=>document.querySelector(`[data-dir="${k}"]`).addEventListener('pointerdown',()=>move(k==='left'?-3:k==='right'?3:0,k==='up'?-3:k==='down'?3:0)));
addEventListener('keydown',e=>{if(e.key==='w'||e.key==='ArrowUp')move(0,-3);if(e.key==='s'||e.key==='ArrowDown')move(0,3);if(e.key==='a'||e.key==='ArrowLeft')move(-3,0);if(e.key==='d'||e.key==='ArrowRight')move(3,0);if(e.key===' '&&state.phase==='battle')resolveBattle()});
canvas.addEventListener('pointerdown',e=>{if(state.phase!=='map')return;let best=null,bd=25;for(const c of cities){let [x,y]=worldToScreen(c.x,c.z),d=Math.hypot(e.clientX-x,e.clientY-y);if(d<bd){bd=d;best=c}}if(best)cityPanel(best)});
document.getElementById('save').onclick=save;document.getElementById('load').onclick=load;document.getElementById('endBattle').onclick=resolveBattle;log('أهلًا بك في فارس الصحراء');render();
setInterval(()=>{if(state.phase==='map'){state.day++;let wage=state.troops.reduce((a,i)=>a+types[i][2],0);if(state.gold>=wage){state.gold-=wage;state.morale=Math.min(100,state.morale+2)}else state.morale-=10;ui();if(Math.random()<.18){let a=1+Math.floor(Math.random()*3),b=0;war(a,b);log('⚔️ اندلعت حرب جديدة')}}},20000);
